version: '3.5'

services:
  facturacion-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: facturacion-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - "8090:80"
    networks:
      backend:
        aliases:
          - facturacion-app

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    expose:
      - 3306
    ports:
      - "8092:3306"
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      backend:
        aliases:
          - mysql-db

  phpadmin:
    image: "phpmyadmin/phpmyadmin"
    ports:
      - "8091:80"
    environment:
      - PMA_HOST=mysql-db
    links:
      - mysql-db
    depends_on:
      - mysql-db
    networks:
      backend:
        aliases:
          - phpadmin

networks:
  backend:
    name: backend-network
